# Generated by Django 4.2.5 on 2023-10-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('abbr', models.CharField(max_length=3, null='true')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=50)),
                ('abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbatest.teams')),
            ],
        ),
    ]
