# Generated by Django 4.2.5 on 2023-10-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbatest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='abbr',
            new_name='teamID',
        ),
        migrations.AlterField(
            model_name='roster',
            name='id',
            field=models.IntegerField(primary_key='true', serialize=False),
        ),
    ]
